import Footer from "../components/Footer";
import Head from "next/head";
import Header from "../components/Header";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";

export default function Municipalite() {
  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider />
      <div className="container" style={{ marginTop: "100px" }}>
        <div className="row">
          <div className="col-sm-12">
            <div className="row">
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Invest</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px"}}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Invest</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px", padding: "1%" }}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Invest</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px"}}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Invest</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px", padding: "1%" }}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
