import Footer from "../components/Footer";
import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
const OwlCarousel = dynamic(import("react-owl-carousel"), { ssr: false });
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";

export default function Municipalite() {
  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <OwlCarousel items={1} className="owl-theme" loop nav margin={0}>
        <div className="item">
          <section className="hero-wrap">
            <div className="hero-mask opacity-7 bg-dark"></div>
            <div
              className="hero-bg"
              style={{ backgroundImage: "url('/time.jpg')" }}
            ></div>
            <div className="hero-content d-flex fullscreen-with-header py-5">
              <div className="container my-auto">
                <div className="row">
                  <div className="col-12 col-lg-8 col-xl-7 text-left text-lg-left">
                    <h2 className="text-22 text-white">Municipalite</h2>
                    <p className="text-3 text-white mb-4">
                      It is a long established fact that a reader will be
                      distracted by the readable content of a page when looking
                      at its layout. The point of using Lorem Ipsum is that it
                      has a more-or-less normal distribution of letters, as
                      opposed to using &apos;Content here, content here&apos;, making it
                      look like readable English.
                    </p>
                    <div className="underline_green"></div>{" "}
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </OwlCarousel>
      <div className="container" style={{ marginTop: "100px" }}>
        <div className="row">
          <div className="col-sm-12">
            <div className="row">
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Did you know?</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px"}}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Did you know?</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px", padding: "1%" }}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Did you know?</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px"}}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
              <div className="col-md-4">
                <div className="web-card">
                  <img src="/time.jpg" alt="Image" />
                  <div className="card-btn-wrapper text-center">
                    <button className="card-btn blue-btn">Did you know?</button>
                  </div>
                  <p
                    className="text-3"
                    style={{ marginTop: "40px", padding: "1%" }}
                  >
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout. The point of using Lorem Ipsum is that it has a
                    more-or-less normal distribution of letters, as opposed to
                    using &apos;Content here, content here&apos;, making it look like
                    readable English.
                  </p>
                  <a href="#" className="find-more">Find More</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
